data_location:
  raw_data_location: data/raw
  test_data_location: data/test
  train_data_location: data/train

split_data:
  test_size: 0.20
  random_state: 20170428

train:
  n_estimators: 100
  min_split: 64