name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          - pip install -r requirements.txt

          # Generate data #TODO: Setup DVC Remote

          - python src/get_data.py --data_location=data/raw

          # Run ML workflow as pipeline
          - dvc repro

          # Use DVC metrics diff to compare metrics to master
          - git fetch --prune
          - echo "## Metrics" >> report.md
          - dvc metrics diff --show-md master >> report.md

          # Add figure to report
          - echo "## Plots" >> report.md

          - dvc plots diff --target prc.json --show-vega master > vega.json
          - vl2png vega.json -s 1.3 | cml-publish --md >> report.md

          - dvc plots diff --target prc.json --show-vega master > vega.json


          # Add report to PR
          - cml-send-comment report.md